// SPDX-License-Identifier: Unlicense OR MIT

package localization

// Texts of what the accounts tell others, AyuGram's Ghost Mode. AyuGram's
// strings are not in Telegram's language pack.
func init() {
	for key, texts := range map[string][2]string{
		"ghost.title":                 {"Режим призрака", "Ghost Mode"},
		"ghost.body":                  {"Что аккаунты сообщают о себе. Без отметок никто не видит, что вы читаете, в сети или печатаете.", "What the accounts tell about themselves. With nothing checked, nobody sees that you read, are online or type."},
		"ghost.read":                  {"Отправлять прочтение", "Send read receipts"},
		"ghost.online":                {"Показывать «в сети»", "Show online"},
		"ghost.typing":                {"Отправлять «печатает»", "Send typing"},
		"ghost.interact":              {"Прочитывать при действии", "Read on interact"},
		"ghost.interact_body":         {"Отмечает чат прочитанным, когда вы отправляете в него сообщение или ставите реакцию.", "Marks a chat read when you send a message to it or react in it."},
		"menu.read":                   {"Прочитать", "Read Message"},
		"menu.edits":                  {"История правок", "Edits History"},
		"menu.filter":                 {"Добавить фильтр", "Add Filter"},
		"menu.repeat":                 {"Повторить", "Repeat Message"},
		"info.username":               {"Имя пользователя · нажмите, чтобы скопировать", "Username · click to copy"},
		"info.username_copied":        {"Имя пользователя скопировано.", "Username copied to clipboard."},
		"info.link_copied":            {"Ссылка скопирована.", "Link copied to clipboard."},
		"info.copy_link":              {"Копировать ссылку", "Copy Link"},
		"viewer.saved":                {"Фото сохранено: {path}", "Photo saved: {path}"},
		"viewer.copied":               {"Фото скопировано в буфер обмена.", "Photo copied to clipboard."},
		"viewer.keep_failed":          {"Не удалось сохранить фото", "Could not keep the photo"},
		"record.voice":                {"Записать голосовое сообщение", "Record voice message"},
		"record.no_ffmpeg":            {"Для записи голосовых сообщений нужен ffmpeg: установите его или укажите путь к нему во внешних интеграциях.", "Recording voice messages needs ffmpeg: install it, or set its path in the external integrations."},
		"record.bad_file":             {"Этот файл не отправить голосовым сообщением: нужен Opus в OGG, MP3 или M4A.", "This file cannot be sent as a voice message: it must be Opus in OGG, MP3 or M4A."},
		"record.audio_files":          {"Аудиофайлы", "Audio files"},
		"info.registration":           {"Дата регистрации (примерно, по ID)", "Registration date (estimated from the ID)"},
		"info.registered_about":       {"~ {date}", "~ {date}"},
		"info.registered_before":      {"раньше {date}", "before {date}"},
		"info.registered_after":       {"позже {date}", "after {date}"},
		"info.dc":                     {"Дата-центр фото профиля", "Profile photo's data center"},
		"info.copied":                 {"Скопировано.", "Copied to clipboard."},
		"confirm.sticker":             {"Отправить этот стикер?", "Do you want to send this sticker?"},
		"confirm.gif":                 {"Отправить этот GIF?", "Do you want to send this GIF?"},
		"confirm.send":                {"Отправить", "Send"},
		"settings.confirm":            {"Подтверждать отправку", "Confirm sending"},
		"settings.confirm_sticker":    {"Стикеров", "Stickers"},
		"settings.confirm_gif":        {"GIF", "GIFs"},
		"shot.title":                  {"Снимок сообщений", "Message Shot"},
		"shot.theme":                  {"Тема", "Theme"},
		"shot.theme_current":          {"Как в приложении", "As in the app"},
		"shot.background":             {"Показывать фон", "Show background"},
		"shot.date":                   {"Показывать дату", "Show date"},
		"shot.reactions":              {"Показывать реакции", "Show reactions"},
		"shot.spoilers":               {"Раскрыть спойлеры", "Reveal spoilers"},
		"shot.copy":                   {"Копировать", "Copy"},
		"shot.save":                   {"Сохранить", "Save"},
		"shot.copied":                 {"Снимок скопирован в буфер обмена.", "The shot was copied to the clipboard."},
		"look.title":                  {"Сообщения и аватары", "Messages and Avatars"},
		"look.preview":                {"Так будут выглядеть сообщения", "Messages will look like this"},
		"look.bubble":                 {"Радиус пузырей", "Message Bubble Radius"},
		"look.avatar":                 {"Скругление аватаров", "Avatar Corners"},
		"look.seconds":                {"Секунды во времени сообщений", "Show Message Seconds"},
		"look.edited_mark":            {"Отметка «изменено»", "Edited Mark"},
		"look.deleted_mark":           {"Отметка «удалено»", "Deleted Mark"},
		"emojipacks.title":            {"Наборы эмодзи", "Emoji Packs"},
		"emojipacks.body":             {"Наборы эмодзи Telegram Desktop: эмодзи рисуются готовыми картинками, как в нём. Набор скачивается один раз и хранится на этом компьютере: Apple — из репозитория Telegram Desktop на GitHub, остальные — с серверов Telegram через ваш аккаунт. Эмодзи, которых в наборе нет, рисует шрифт эмодзи из раздела «Шрифты» или системный.", "The emoji sets of Telegram Desktop: emoji are drawn as ready pictures, the way it draws them. A pack is downloaded once and kept on this computer: Apple from Telegram Desktop's repository on GitHub, the others from Telegram's servers through your account. Emoji a pack lacks are drawn by the emoji font of the Fonts section, or the system's."},
		"emojipacks.none":             {"Без набора", "No Pack"},
		"emojipacks.none_hint":        {"Системный шрифт эмодзи или свой файл из раздела «Шрифты».", "The system's emoji font, or a file of your own from the Fonts section."},
		"emojipacks.font":             {"шрифт", "font"},
		"emojipacks.sprites":          {"спрайты", "sprites"},
		"emojipacks.download":         {"Скачать", "Download"},
		"emojipacks.update":           {"Обновить", "Update"},
		"emojipacks.use":              {"Выбрать", "Use"},
		"emojipacks.used":             {"Выбран", "In Use"},
		"emojipacks.remove":           {"Удалить", "Delete"},
		"emojipacks.cancel":           {"Отмена", "Cancel"},
		"emojipacks.progress":         {"Скачивается: {percent}%", "Downloading: {percent}%"},
		"emojipacks.update_available": {"Есть новая версия.", "There is a newer version."},
		"emojipacks.not_in_catalog":   {"Этого набора больше нет в списке: скачать его заново не получится.", "This pack is no longer listed: it cannot be downloaded again."},
		"emojipacks.failed":           {"Не удалось", "Failed"},
		"emojipacks.needs_telegram":   {"Этот набор скачивается с серверов Telegram: нужен подключённый аккаунт.", "This pack is downloaded from Telegram's servers: a connected account is needed."},
		"emojipacks.reading":          {"Читаю список наборов…", "Reading the list of packs…"},
		"emojipacks.offer_title":      {"Эмодзи не отображаются", "Emoji Are Not Shown"},
		"emojipacks.offer_body":       {"В системе нет шрифта эмодзи, и вместо них видны квадраты. Скачать набор эмодзи Apple ({size})? Его можно сменить или удалить в Настройках → Оформление.", "The system has no emoji font, and squares are shown instead of emoji. Download the Apple emoji pack ({size})? It can be changed or deleted in Settings → Appearance."},
		"emojipacks.offer_later":      {"Не сейчас", "Not Now"},
		"emojipacks.offer_started":    {"Набор эмодзи Apple скачивается и будет выбран, когда скачается.", "The Apple emoji pack is downloading, and will be used once it is downloaded."},
		"emojipacks.catalog_failed":   {"Список наборов недоступен", "The list of packs is not available"},
		"fonts.title":                 {"Шрифты", "Fonts"},
		"fonts.body":                  {"Свои файлы шрифтов (TTF, OTF и их коллекции) используются раньше системных. Файл остаётся на месте: если его убрать, вернётся системный шрифт. Один файл — одно начертание: без отдельного полужирного файла полужирный текст рисуется обычным.", "Font files of your own (TTF, OTF and their collections) are used before the system's. A file stays where it is: once it is gone, the system's font is back. One file is one style: without a bold file of its own, bold text is drawn regular."},
		"fonts.text":                  {"Основной шрифт", "Text Font"},
		"fonts.text_hint":             {"Весь текст интерфейса и сообщений.", "All the text of the interface and of messages."},
		"fonts.extra":                 {"Дополнительный шрифт", "Additional Font"},
		"fonts.extra_hint":            {"Символы, которых нет в основном, до системных шрифтов: например, китайский, японский или корейский.", "Characters the text font lacks, before the system's fonts: Chinese, Japanese or Korean, for one."},
		"fonts.mono":                  {"Моноширинный шрифт", "Monospace Font"},
		"fonts.mono_hint":             {"Код в сообщениях.", "Code in messages."},
		"fonts.emoji":                 {"Шрифт эмодзи", "Emoji Font"},
		"fonts.emoji_hint":            {"Эмодзи в тексте, реакциях и панели выбора.", "Emoji in text, reactions and the picker."},
		"fonts.system":                {"Системный", "The system's"},
		"fonts.from_env":              {"Задан переменной окружения", "Set by an environment variable"},
		"fonts.choose":                {"Выбрать файл", "Choose a File"},
		"fonts.reset":                 {"Сбросить", "Reset"},
		"fonts.rejected":              {"Файл не подошёл", "The file was turned down"},
		"fonts.not_a_font":            {"это не шрифт TrueType или OpenType", "it is not a TrueType or OpenType font"},
		"fonts.no_emoji":              {"в шрифте нет эмодзи", "the font has no emoji"},
		"fonts.too_large":             {"файл больше 128 МБ", "the file is over 128 MB"},
		"size.bytes":                  {"Б", "B"},
		"size.kilobytes":              {"КБ", "KB"},
		"size.megabytes":              {"МБ", "MB"},
		"fonts.missing":               {"файл не найден", "the file is not found"},
		"privacy.streamer":            {"Режим стримера", "Streamer Mode"},
		"privacy.streamer_body":       {"Окна мессенджера не попадают в запись и трансляцию экрана: там, где они, будет пусто. Как режим стримера AyuGram.", "The messenger's windows stay out of screen recordings and streams, which show nothing where they are, as AyuGram's Streamer Mode."},
		"filters.added":               {"Фильтр добавлен в общие.", "Filter added to the shared filters."},
		"filters.title":               {"Фильтры сообщений", "Message Filters"},
		"filters.body":                {"Скрывают чужие сообщения, в которых находится выражение (синтаксис Go regexp), или, «наоборот», не находится.", "Hide others' messages an expression (Go regexp syntax) finds, or, reversed, does not."},
		"filters.enable":              {"Включить фильтры", "Enable Filters"},
		"filters.in_chats":            {"Общие фильтры и в чатах", "Shared Filters in Chats Too"},
		"filters.blocked":             {"Скрывать от заблокированных", "Hide from Blocked Users"},
		"filters.channels_only":       {"Без «в чатах» фильтры действуют только в каналах. Меню чата показывает скрытое.", "Without chats, filters apply in channels only. The chat's menu shows what they hid."},
		"filters.expression":          {"Выражение", "Expression"},
		"filters.reversed":            {"Наоборот", "Reversed"},
		"filters.case":                {"Без учёта регистра", "Case insensitive"},
		"filters.add":                 {"Добавить", "Add"},
		"filters.error":               {"Ошибка в выражении", "Regex syntax error"},
		"filters.empty":               {"Фильтров пока нет.", "No filters here yet."},
		"filters.one_chat":            {"в одном чате", "in one chat"},
		"filters.delete":              {"Удалить фильтр", "Delete filter"},
		"chat_menu.show_filtered":     {"Показать отфильтрованные", "Show Filtered Messages"},
		"chat_menu.hide_filtered":     {"Скрыть отфильтрованные", "Hide Filtered Messages"},
		"edits.title":                 {"История правок", "Edits History"},
		"edits.current":               {"сейчас", "now"},
		"edits.none":                  {"Прежние версии не сохранены: сообщение изменили до того, как оно попало в кеш, или без изменения текста.", "No earlier versions were kept: the message was edited before it was cached, or without changing its text."},
		"edits.failed":                {"Не удалось прочитать историю правок", "Could not read the edits history"},
		"history.deleted_mark":        {"🧹", "🧹"},
		"keep.title":                  {"Сохранение сообщений", "Keeping messages"},
		"keep.body":                   {"Кеш на этом компьютере помнит то, что в Telegram удалили или изменили.", "The cache on this computer remembers what was deleted or changed in Telegram."},
		"keep.deleted":                {"Сохранять удалённые сообщения", "Save deleted messages"},
		"keep.edits":                  {"Сохранять историю правок", "Save edits history"},
		"keep.deleted_body":           {"Удалённые сообщения остаются в истории с отметкой 🧹; в чатах с ботами не сохраняются. Ваши собственные удаления стирают сообщения.", "Deleted messages stay in the history marked 🧹, but in chats with bots. Your own deletions erase messages."},
	} {
		russian[key], english[key] = texts[0], texts[1]
	}
}
